const groups=[{title:'Esfihas salgadas',price:'R$ 4,50',items:[['carne','Carne','Temperada, suculenta e assada na hora.'],['queijo','Queijo','Cremosa e dourada, do jeito que você gosta.'],['frango','Frango','Leve, saborosa e cheia de recheio.'],['calabresa','Calabresa','Sabor marcante em cada mordida.'],['frango-requeijao','Frango com requeijão','A combinação cremosa que conquista.','R$ 5,00'],['pizza','Pizza','O sabor da pizza no formato que você ama.','R$ 5,00'],['bacon','Bacon','Crocante e cheio de sabor.'],['bacon-cheddar','Bacon com cheddar','Bacon crocante com cheddar cremoso.','R$ 5,00'],['porquinho','Porquinho','Bacon com calabresa para quem gosta de sabor marcante.','R$ 6,00']]},{title:'Esfihas doces',price:'R$ 5,00',items:[['chocolate','Chocolate','Doce na medida para fechar o pedido.'],['seducao','Sedução','Chocolate branco com morango.','R$ 6,00'],['doce-leite','Doce de leite','Cremosa, delicada e irresistível.'],['banana-canela','Banana com canela','Aquele aroma gostoso de receita caseira.'],['romeu-julieta','Romeu e Julieta','Queijo com goiabada.','R$ 6,00']]},{title:'Shawarma',items:[['shawarma-frango','Shawarma de frango','Recheado e temperado para matar a fome.'],['shawarma-carne','Shawarma de carne','Sabor intenso e uma refeição completa.']]}];
const catalog=groups.flatMap(g=>g.items.map(([id,name,description])=>({id,name,description,category:g.title})));const cart=new Map();
document.querySelector('#products').innerHTML=groups.map((g,i)=>`<section class="category"><div class="category-title"><span>0${i+1}</span><h3>${g.title}</h3></div>${g.items.map(([id,name,description,price])=>`<article class="product"><div><h4>${name}</h4><p>${description}</p><span class="price">${price||g.price||(id==='shawarma-frango'?'R$ 19,99':'R$ 24,99')}</span></div><button class="add" data-add="${id}" aria-label="Adicionar ${name} — ${g.title}">+</button></article>`).join('')}</section>`).join('');
function change(id,delta){if(!catalog.some(p=>p.id===id)||!Number.isInteger(delta))throw new Error('Produto ou quantidade inválidos.');const q=(cart.get(id)||0)+delta;if(q>99)throw new Error('Limite de 99 unidades por produto.');if(q<=0)cart.delete(id);else cart.set(id,q);render();}
function snapshot(){return [...cart].map(([id,quantity])=>({id,name:catalog.find(p=>p.id===id).name,quantity}));}
function render(){const rows=snapshot();const count=rows.reduce((s,x)=>s+x.quantity,0);document.querySelector('#count').textContent=count;document.querySelector('#checkout').disabled=count===0;document.querySelector('#bag-items').innerHTML=rows.length?rows.map(p=>`<div class="cart-row"><strong>${p.name}</strong><div class="quantity"><button data-change="${p.id}" data-delta="-1" aria-label="Remover uma unidade de ${p.name}">−</button><span aria-label="Quantidade">${p.quantity}</span><button data-change="${p.id}" data-delta="1" aria-label="Adicionar uma unidade de ${p.name}">+</button></div></div>`).join(''):'<div class="empty">Seu pedido começa por aqui.<br>Toque no + ao lado de um sabor.</div>';document.querySelector('#announcement').textContent=`${count} itens no pedido.`;}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');const edit=e.target.closest('[data-change]');try{if(add)change(add.dataset.add,1);if(edit)change(edit.dataset.change,Number(edit.dataset.delta));}catch(error){document.querySelector('#announcement').textContent=error.message;}});
document.querySelector('#checkout').addEventListener('click',()=>{const rows=snapshot();if(!rows.length)return;const notes=document.querySelector('#notes').value.trim();const message=['Olá, Sahara! Gostaria de consultar este pedido:','',...rows.map(p=>`${p.quantity}x ${p.name}`),...(notes?['',`Observações: ${notes}`]:[]),'','Podem confirmar a disponibilidade, o valor total e as opções de entrega ou retirada?'].join('\n');window.open('https://wa.me/5544991748318?text='+encodeURIComponent(message),'_blank','noopener,noreferrer');});render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'stage_sahara_order',title:'Montar pedido Sahara',description:'Substitui a seleção visível de produtos. Não envia o pedido. O cliente pode revisar e abrir o WhatsApp.',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string',enum:catalog.map(p=>p.id)},quantity:{type:'integer',minimum:1,maximum:99}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.items)||input.items.length>catalog.length)throw new Error('Lista inválida.');const staged=new Map();for(const item of input.items){if(!catalog.some(p=>p.id===item.id)||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99||staged.has(item.id))throw new Error('Item inválido ou duplicado.');staged.set(item.id,item.quantity);}cart.clear();for(const [id,q] of staged)cart.set(id,q);render();return {items:snapshot(),sent:false};}})).catch(()=>{});}catch{}}

