const productPhotos={"carne":{"file":"carne","y":718,"h":692},"frango-catupiry":{"file":"frango-catupiry","y":718,"h":692},"bacon-queijo":{"file":"bacon-queijo","y":758,"h":613},"frango-bacon":{"file":"frango-bacon","y":718,"h":692},"calabresa-catupiry":{"file":"calabresa-catupiry","y":718,"h":692},"queijo":{"file":"queijo","y":538,"h":519,"w":691,"totalH":1536},"brocolis-queijo":{"file":"brocolis-queijo","y":538,"h":519,"w":691,"totalH":1536}};
function productPhoto(id,name){const p=productPhotos[id];if(!p)return '';const w=p.w||921,fullH=p.totalH||2048;return `<div class="product-photo" style="aspect-ratio:${w}/${p.h}"><img src="images/${p.file}.jpg" alt="Esfiha de ${name}" loading="lazy" decoding="async" width="${w}" height="${fullH}" style="top:-${p.y/p.h*100}%"></div>`;}

const groups=[{"title":"Combos","items":[["combo-10","Combo 10 — 10 esfihas de carne","10 esfihas de carne.","R$ 35,00"],["combo-15","Combo 15 — 15 esfihas de carne","15 esfihas de carne.","R$ 52,00"],["combo-mix-10","Combo Mix 10","5 de carne + 3 de frango + 2 de calabresa.","R$ 38,00"],["combo-mix-15","Combo Mix 15","5 de carne + 5 de frango + 5 de calabresa.","R$ 55,00"],["combo-familia-20","Combo Família 20","10 de carne + 5 de frango + 5 de calabresa.","R$ 72,00"],["combo-especial","Combo Especial — 40 esfihas + refrigerante 2 L","40 esfihas sortidas + refrigerante de 2 litros.","R$ 135,00"]]},{"title":"Bebidas","items":[["coca-350","Coca-Cola lata 350 ml","Lata de 350 ml.","R$ 6,00"],["coca-zero-350","Coca-Cola Zero lata 350 ml","Lata de 350 ml, zero açúcar.","R$ 6,00"],["guarana-350","Guaraná Antarctica lata 350 ml","Lata de 350 ml.","R$ 6,00"],["agua-500","Água mineral 500 ml","Garrafa de 500 ml.","R$ 4,00"],["refri-2l","Refrigerante 2 L","Consulte os sabores disponíveis.","R$ 14,00"]]},{title:'Esfihas salgadas',price:'R$ 4,50',items:[['carne','Carne','Temperada, suculenta e assada na hora.'],['queijo','Queijo','Cremosa e dourada, do jeito que você gosta.'],['frango','Frango','Leve, saborosa e cheia de recheio.'],['calabresa','Calabresa','Sabor marcante em cada mordida.'],['frango-requeijao','Frango com requeijão','A combinação cremosa que conquista.','R$ 5,00'],['pizza','Pizza','O sabor da pizza no formato que você ama.','R$ 5,00'],['bacon','Bacon','Crocante e cheio de sabor.'],['bacon-cheddar','Bacon com cheddar','Bacon crocante com cheddar cremoso.','R$ 5,00'],['porquinho','Porquinho','Bacon com calabresa para quem gosta de sabor marcante.','R$ 6,00']]},{title:'Esfihas doces',price:'R$ 5,00',items:[['chocolate','Chocolate','Doce na medida para fechar o pedido.'],['seducao','Sedução','Chocolate branco com morango.','R$ 6,00'],['doce-leite','Doce de leite','Cremosa, delicada e irresistível.'],['romeu-julieta','Romeu e Julieta','Queijo com goiabada.','R$ 6,00']]},{title:'Shawarma',items:[['shawarma-frango','Shawarma de frango','Recheado e temperado para matar a fome.'],['shawarma-carne','Shawarma de carne','Sabor intenso e uma refeição completa.']]}];
groups.find(g=>g.title==='Esfihas salgadas').items.push(...[["frango-catupiry","Frango com Catupiry","Frango temperado e desfiado com Catupiry.","R$ 4,00"],["calabresa-mussarela","Calabresa com mussarela","Calabresa com mussarela.","R$ 4,00"],["bacon-queijo","Bacon com queijo","Mussarela com bacon.","R$ 4,50"],["frango-bacon","Frango com bacon","Frango com bacon.","R$ 5,00"],["calabresa-catupiry","Calabresa com Catupiry","Calabresa com Catupiry.","R$ 4,00"],["calabresa-acebolada","Calabresa acebolada","Calabresa com cebola.","R$ 4,00"],["lombo-catupiry","Lombo com Catupiry","Lombo com Catupiry.","R$ 5,00"],["coalhada","Coalhada","Recheio de coalhada.","R$ 4,00"],["brocolis-queijo","Brócolis com queijo","Brócolis com queijo.","R$ 4,00"],["palmito-queijo","Palmito com queijo","Palmito com queijo.","R$ 4,50"],["vegetariana","Vegetariana","Queijo, palmito e brócolis.","R$ 5,00"],["brocolis-bacon-queijo","Brócolis com bacon e queijo","Brócolis, bacon e queijo.","R$ 5,00"],["frango-cheddar-bacon","Frango com cheddar e bacon","Frango, cheddar e bacon.","R$ 5,00"],["strogonoff-carne","Strogonoff de carne","Recheio de strogonoff de carne.","R$ 5,50"],["texana","Texana","","R$ 5,00"],["bahiana","Bahiana","","R$ 5,00"]]);
groups.find(g=>g.title==='Esfihas doces').items.push(...[["brigadeiro","Brigadeiro","Creme de avelã com granulado de chocolate.","R$ 5,50"],["beijinho","Beijinho","Chocolate branco com coco ralado.","R$ 5,00"],["sensacao","Sensação","Creme de avelã com morango.","R$ 5,50"],["bombom-branco","Bombom branco","Chocolate branco com bombom branco sabor beijinho.","R$ 5,50"],["kitkat","KitKat","Creme de avelã com KitKat.","R$ 4,50"],["banoffee","Banoffee","","R$ 5,50"],["charge","Charge","Creme de avelã com granulado de amendoim.","R$ 5,00"],["leite-ninho","Leite Ninho","Chocolate branco com Leite Ninho.","R$ 5,00"]]);
const categoryOrder=["Esfihas salgadas","Esfihas doces","Combos","Bebidas","Shawarma"];
groups.sort((a,b)=>categoryOrder.indexOf(a.title)-categoryOrder.indexOf(b.title));
const catalog=groups.flatMap(g=>g.items.map(([id,name,description])=>({id,name,description,category:g.title})));const cart=new Map();
document.querySelector('#products').innerHTML=groups.map((g,i)=>`<section class="category"><div class="category-title"><span>0${i+1}</span><h3>${g.title}</h3></div>${g.items.map(([id,name,description,price])=>`<article class="product${productPhotos[id]?' has-photo':''}">${productPhoto(id,name)}<div class="product-info"><h4>${name}</h4><p>${description}</p><span class="price">${price||g.price||(id==='shawarma-frango'?'R$ 19,99':'R$ 24,99')}</span></div><div class="quantity product-quantity" role="group" aria-label="Quantidade de ${name} — ${g.title}"><button type="button" data-change="${id}" data-delta="-1" aria-label="Diminuir ${name} — ${g.title}" disabled>−</button><output data-quantity="${id}" aria-label="Quantidade de ${name}">0</output><button type="button" data-change="${id}" data-delta="1" aria-label="Adicionar ${name} — ${g.title}">+</button></div></article>`).join('')}</section>`).join('');
function change(id,delta){if(!catalog.some(p=>p.id===id)||!Number.isInteger(delta))throw new Error('Produto ou quantidade inválidos.');const q=(cart.get(id)||0)+delta;if(q>99)throw new Error('Limite de 99 unidades por produto.');if(q<=0)cart.delete(id);else cart.set(id,q);render();}
function snapshot(){return [...cart].map(([id,quantity])=>({id,name:catalog.find(p=>p.id===id).name,quantity}));}
function render(){for(const product of catalog){const quantity=cart.get(product.id)||0;const output=document.querySelector('[data-quantity="'+product.id+'"]');output.value=String(quantity);const controls=output.parentElement;controls.querySelector('[data-delta="-1"]').disabled=quantity===0;controls.querySelector('[data-delta="1"]').disabled=quantity===99;controls.classList.toggle('has-items',quantity>0);}const rows=snapshot();const count=rows.reduce((s,x)=>s+x.quantity,0);document.querySelector('#count').textContent=count;document.querySelector('#checkout').disabled=count===0;document.querySelector('#bag-items').innerHTML=rows.length?rows.map(p=>`<div class="cart-row"><strong>${p.name}</strong><div class="quantity"><button data-change="${p.id}" data-delta="-1" aria-label="Remover uma unidade de ${p.name}">−</button><span aria-label="Quantidade">${p.quantity}</span><button data-change="${p.id}" data-delta="1" ${p.quantity>=99?'disabled':''} aria-label="Adicionar uma unidade de ${p.name}">+</button></div></div>`).join(''):'<div class="empty">Seu pedido começa por aqui.<br>Toque no + ao lado de um sabor.</div>';document.querySelector('#announcement').textContent=`${count} itens no pedido.`;}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');const edit=e.target.closest('[data-change]');try{if(add)change(add.dataset.add,1);if(edit)change(edit.dataset.change,Number(edit.dataset.delta));}catch(error){document.querySelector('#announcement').textContent=error.message;}});
document.querySelector('#checkout').addEventListener('click',()=>{const rows=snapshot();if(!rows.length)return;const delivery=document.querySelector('input[name="fulfillment"]').value==='delivery';const street=document.querySelector('#street');const houseNumber=document.querySelector('#house-number');street.value=street.value.trim();houseNumber.value=houseNumber.value.trim();if(!document.querySelector('#delivery-form').reportValidity())return;const addressLines=delivery?['','Entrega',`Rua: ${street.value}`,`Número: ${houseNumber.value}`,'Taxa de entrega: grátis na região de Maringá.']:['','Retirada na loja'];const payment=document.querySelector('input[name="payment"]:checked')?.value;const notes=document.querySelector('#notes').value.trim();const message=['Olá, Sahara! Gostaria de consultar este pedido:','',...rows.map(p=>`${p.quantity}x ${p.name}`),...addressLines,...(payment?['',`Forma de pagamento: ${payment}`]:[]),...(notes?['',`Observações: ${notes}`]:[]),'',delivery?'Podem confirmar a disponibilidade, o valor total e a entrega neste endereço?':'Podem confirmar a disponibilidade, o valor total e o horário para retirada?'].join('\n');window.open('https://wa.me/5544991748318?text='+encodeURIComponent(message),'_blank','noopener,noreferrer');});render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'stage_sahara_order',title:'Montar pedido Sahara',description:'Substitui a seleção visível de produtos. Não envia o pedido. O cliente pode revisar e abrir o WhatsApp.',inputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string',enum:catalog.map(p=>p.id)},quantity:{type:'integer',minimum:1,maximum:99}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!Array.isArray(input.items)||input.items.length>catalog.length)throw new Error('Lista inválida.');const staged=new Map();for(const item of input.items){if(!catalog.some(p=>p.id===item.id)||!Number.isInteger(item.quantity)||item.quantity<1||item.quantity>99||staged.has(item.id))throw new Error('Item inválido ou duplicado.');staged.set(item.id,item.quantity);}cart.clear();for(const [id,q] of staged)cart.set(id,q);render();return {items:snapshot(),sent:false};}})).catch(()=>{});}catch{}}


const deliveryForm=document.querySelector('#delivery-form');
deliveryForm.addEventListener('submit',event=>event.preventDefault());
deliveryForm.addEventListener('change',()=>{const delivery=document.querySelector('input[name="fulfillment"]').value==='delivery';document.querySelector('#delivery-address').hidden=!delivery;for(const id of ['#street','#house-number']){const field=document.querySelector(id);field.disabled=!delivery;field.required=delivery;}});
